---
functional:
  - Пользователь должен иметь возможность регистрации через электронную почту 
  - Пользователь должен иметь возможность регистрации через GitHub
  - Пользователь должен иметь возможность авторизации
  - Пользователь должен иметь возможность просмотреть историю сыгранных матчей 
  - Пользователь должен иметь возможность просмотреть личный рейтинг
  - Пользователь может посмотреть статистику другого пользователя
  - Пользователь может выбрать уровень "сражения" 
  - Пользователь может просмотреть "сражение" в записи
  - Пользователь может выбрать вариант игры с другим пользователем 
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика (не менее 1000 пользователей)
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть удобным на мобильном устройстве
implicit: 
  - Пользователь может перейти в телеграм-канал, посвященный приложению
  - Пользователь может выбрать максимальную продолжительность игры

